[build-system]
requires = [
  "setuptools",
  "wheel",
  "scikit-build>=0.11.0,<0.14",
  "cmake",
  "ninja"
]


[tool.cibuildwheel]
test-command = "pytest test -vv"

[tool.cibuildwheel.linux]
archs = "auto aarch64 ppc64le s390x"

[tool.cibuildwheel.macos]
arches = "x86_64 arm64"