[build-system]
requires = [
  "setuptools",
  "wheel",
  "scikit-build>=0.11.0,<0.14",
  "cmake",
  "ninja"
]

[tool.cibuildwheel]
test-command = "pip install pytest nbval && pytest -vv {package}/test"

[tool.cibuildwheel.linux]
archs = "auto aarch64"
