name: Build Wheel

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


jobs:
  osx:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.7", "3.8", "3.9", "3.10"]

    env:
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      CXX: clang++
      CC: clang

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.PYTHON_VERSION }}

    - name: Setup xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '10.3'

    - name: Build wheel
      run: |
        export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
        python -m pip wheel . --verbose -w wheelhouse

    - name: List wheels
      run: ls wheelhouse

    - uses: actions/upload-artifact@v2
      with:
        name: wheelhouse
        path: wheelhouse/xeus_python-*.whl
        if-no-files-found: error

  linux:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.7", "3.8", "3.9", "3.10"]

    container:
        image: "quay.io/pypa/manylinux2014_x86_64"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build wheel
      run: |
        pyver=`echo '${{ matrix.PYTHON_VERSION }}' | tr -d '.'`
        pypath=`echo /opt/python/cp${pyver}-cp${pyver}*/bin`
        export PATH=$pypath:$PATH
        python -m pip wheel --verbose . -w wheelhouse_dirty
        auditwheel repair wheelhouse_dirty/xeus_python-*.whl --plat manylinux2014_x86_64 -w wheelhouse

    - name: List wheels
      run: ls wheelhouse

    - uses: actions/upload-artifact@v2
      with:
        name: wheelhouse
        path: wheelhouse/xeus_python-*.whl
        if-no-files-found: error

  windows:
    runs-on: windows-2019

    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.PYTHON_VERSION }}

    - name: Setup NASM
      uses: ilammy/setup-nasm@v1

    - name: Build wheel
      shell: cmd
      run: |
        call "c:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        pip wheel --verbose . -w wheelhouse

    - name: List wheels
      run: ls wheelhouse

    - uses: actions/upload-artifact@v2
      with:
        name: wheelhouse
        path: wheelhouse/xeus_python-*.whl
        if-no-files-found: error

  test-wheel:
    runs-on: ${{ matrix.os }}-latest
    needs: [linux, osx, windows]

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        PYTHON_VERSION: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - PYTHON_VERSION: "3.7"
            os: ubuntu
            whl: 'xeus_python-*-cp37*linux*.whl'
          - PYTHON_VERSION: "3.8"
            os: ubuntu
            whl: 'xeus_python-*-cp38*linux*.whl'
          - PYTHON_VERSION: "3.9"
            os: ubuntu
            whl: 'xeus_python-*-cp39*linux*.whl'
          - PYTHON_VERSION: "3.10"
            os: ubuntu
            whl: 'xeus_python-*-cp310*linux*.whl'
          - PYTHON_VERSION: "3.7"
            os: macos
            whl: 'xeus_python-*-cp37*macos*.whl'
          - PYTHON_VERSION: "3.8"
            os: macos
            whl: 'xeus_python-*-cp38*macos*.whl'
          - PYTHON_VERSION: "3.9"
            os: macos
            whl: 'xeus_python-*-cp39*macos*.whl'
          - PYTHON_VERSION: "3.10"
            os: macos
            whl: 'xeus_python-*-cp310*macos*.whl'
          - PYTHON_VERSION: "3.7"
            os: windows
            whl: 'xeus_python-*-cp37*win*.whl'
          - PYTHON_VERSION: "3.8"
            os: windows
            whl: 'xeus_python-*-cp38*win*.whl'
          - PYTHON_VERSION: "3.9"
            os: windows
            whl: 'xeus_python-*-cp39*win*.whl'
          - PYTHON_VERSION: "3.10"
            os: windows
            whl: 'xeus_python-*-cp310*win*.whl'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: wheelhouse
        path: ./wheelhouse

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.PYTHON_VERSION }}

    - name: Install deps
      run: python -m pip install pytest nbval

    - name: List wheels
      run: ls wheelhouse

    - name: Install wheel
      shell: bash
      run: |
        WHEEL=$(find . -type f -iname ${{ matrix.whl }})
        python -m pip install -vv ${WHEEL}
      working-directory: wheelhouse

    - name: Run test
      run: pytest test -vv
